import { marked } from 'marked';
import './ContentStyles.css';

function countWords(sections, abstract, conclusion) {
  let total = (abstract || '').split(/\s+/).length + (conclusion || '').split(/\s+/).length;
  (sections || []).forEach(s => { total += (s.content || '').split(/\s+/).length; });
  return total;
}

export default function Report({ data, depthMode }) {
  if (!data) return null;
  const sections = data.sections || [];
  const refs = data.references || [];
  const wordCount = countWords(sections, data.abstract, data.conclusion);
  const readTime = Math.max(1, Math.ceil(wordCount / 200));

  return (
    <div>
      <h2 className="section-title">{data.title || 'Report'}</h2>
      <p className="section-subtitle">
        {depthMode ? 'In-depth academic report with comprehensive analysis' : 'In-depth academic report generated by AI'}
      </p>

      {/* Depth mode meta bar */}
      {depthMode && (
        <div className="depth-meta-bar">
          <div className="depth-meta-item"><span>📄</span> <strong>{sections.length}</strong> sections</div>
          <div className="depth-meta-item"><span>📝</span> <strong>~{wordCount.toLocaleString()}</strong> words</div>
          <div className="depth-meta-item"><span>⏱️</span> <strong>~{readTime}</strong> min read</div>
          <div className="depth-meta-item"><span>📚</span> <strong>{refs.length}</strong> references</div>
        </div>
      )}

      {/* Depth mode TOC */}
      {depthMode && sections.length > 0 && (
        <div className="depth-toc">
          <div className="depth-toc__title">📋 Table of Contents</div>
          <div className="depth-toc__list">
            <div className="depth-toc__item"><span className="depth-toc__num">•</span><span>Abstract</span></div>
            {sections.map((sec, i) => (
              <div key={i} className="depth-toc__item">
                <span className="depth-toc__num">{i + 1}</span>
                <span>{sec.heading}</span>
              </div>
            ))}
            <div className="depth-toc__item"><span className="depth-toc__num">•</span><span>Conclusion</span></div>
            <div className="depth-toc__item"><span className="depth-toc__num">•</span><span>References ({refs.length})</span></div>
          </div>
        </div>
      )}

      {/* Abstract */}
      {data.abstract && (
        <div className="intro-card">
          <div style={{ fontSize: '0.75rem', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.06em', color: 'var(--accent-cyan)', marginBottom: 8 }}>
            📄 Abstract
          </div>
          {data.abstract}
        </div>
      )}

      {depthMode && <div className="depth-progress"><div className="depth-progress__fill" style={{ width: '100%' }} /></div>}

      {/* Sections */}
      {sections.map((sec, i) => (
        <div key={i} className="content-card stagger-item" style={{ animationDelay: `${i * 0.08}s` }}>
          <div className="content-card__header">
            <div className="content-card__number">{i + 1}</div>
            <h3 className="content-card__title">{sec.heading}</h3>
            {depthMode && (
              <span className="difficulty-badge difficulty-badge--expert" style={{ marginLeft: 'auto' }}>
                📊 Detailed
              </span>
            )}
          </div>
          <div className="content-card__body markdown-body" dangerouslySetInnerHTML={{ __html: marked.parse(sec.content || '') }} />
        </div>
      ))}

      {/* Conclusion */}
      {data.conclusion && (
        <div className="summary-card">
          <div className="summary-card__label">🎯 Conclusion</div>
          <div className="summary-card__text">{data.conclusion}</div>
        </div>
      )}

      {/* References */}
      {refs.length > 0 && (
        <div className="content-card" style={{ marginTop: 16 }}>
          <h3 className="content-card__title" style={{ marginBottom: 12 }}>📚 References</h3>
          <ol style={{ paddingLeft: '1.5em', color: 'var(--text-muted)', fontSize: '0.9rem' }}>
            {refs.map((ref, i) => (
              <li key={i} style={{ marginBottom: 6, lineHeight: 1.5 }}>{ref}</li>
            ))}
          </ol>
        </div>
      )}
    </div>
  );
}
