import { marked } from 'marked';
import './ContentStyles.css';

function estimateReadingTime(sections) {
  const words = sections.reduce((sum, s) => sum + (s.content || '').split(/\s+/).length, 0);
  return Math.max(1, Math.ceil(words / 200));
}

export default function StudyGuide({ data, depthMode }) {
  if (!data) return null;
  const sections = data.sections || [];
  const readTime = estimateReadingTime(sections);
  const wordCount = sections.reduce((sum, s) => sum + (s.content || '').split(/\s+/).length, 0);

  return (
    <div>
      <h2 className="section-title">{data.title || 'Study Guide'}</h2>
      <p className="section-subtitle">
        {depthMode ? 'Deep-dive comprehensive guide generated by AI' : 'Comprehensive guide generated by AI'}
      </p>

      {/* Depth mode meta bar */}
      {depthMode && (
        <div className="depth-meta-bar">
          <div className="depth-meta-item"><span>📖</span> <strong>{sections.length}</strong> sections</div>
          <div className="depth-meta-item"><span>📝</span> <strong>~{wordCount.toLocaleString()}</strong> words</div>
          <div className="depth-meta-item"><span>⏱️</span> <strong>~{readTime}</strong> min read</div>
          <div className="depth-meta-item"><span>🌀</span> <strong>Deep</strong> analysis</div>
        </div>
      )}

      {/* Depth mode table of contents */}
      {depthMode && sections.length > 0 && (
        <div className="depth-toc">
          <div className="depth-toc__title">📋 Table of Contents</div>
          <div className="depth-toc__list">
            {sections.map((sec, i) => (
              <div key={i} className="depth-toc__item">
                <span className="depth-toc__num">{i + 1}</span>
                <span>{sec.heading}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {data.introduction && (
        <div className="intro-card">{data.introduction}</div>
      )}

      {/* Depth mode progress bar */}
      {depthMode && <div className="depth-progress"><div className="depth-progress__fill" style={{ width: '100%' }} /></div>}

      {sections.map((sec, i) => (
        <div
          key={i}
          className="content-card stagger-item"
          style={{ animationDelay: `${i * 0.08}s` }}
        >
          <div className="content-card__header">
            <div className="content-card__number">{i + 1}</div>
            <h3 className="content-card__title">{sec.heading}</h3>
            {depthMode && (
              <span className="difficulty-badge difficulty-badge--expert" style={{ marginLeft: 'auto' }}>
                ⚡ In-depth
              </span>
            )}
          </div>
          <div
            className="content-card__body markdown-body"
            dangerouslySetInnerHTML={{ __html: marked.parse(sec.content || '') }}
          />
          {sec.keyTakeaway && (
            <div className="highlight-box">
              <div className="highlight-box__label">💡 Key Takeaway</div>
              <div className="highlight-box__text">{sec.keyTakeaway}</div>
            </div>
          )}
        </div>
      ))}

      {data.summary && (
        <div className="summary-card">
          <div className="summary-card__label">📋 Summary</div>
          <div className="summary-card__text">{data.summary}</div>
        </div>
      )}
    </div>
  );
}
